app = "craftd"
primary_region = "lax"

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "15s"
    timeout = "10s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/app/build/client"
  url_prefix = "/assets/" 