import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("/login", "routes/login.tsx"),
  route("/account", "routes/account.tsx"),
  route("/health", "routes/health.ts"),
  route("/api/portfolio/:userId", "routes/api.portfolio.$userId.ts"),
  route("/api/resume/convert", "routes/api.resume.convert.ts"),
  route("/api/validate-slug", "routes/api.validate-slug.ts"),
  route("/auth/callback", "routes/auth.callback.ts"),
  route("/onboarding", "routes/onboarding.tsx"),
  route("/onboarding/complete", "routes/onboarding.complete.tsx"),
  route("/demo", "routes/demo.tsx"),
  route("/job-applications", "routes/job-applications.tsx"),
  route("/job-applications/create", "routes/job-applications.create.tsx"),
  route("/job-applications/:id", "routes/job-applications.$id.tsx"),
  route("/api/resume/customize", "routes/api.resume.customize.ts"),
  route("/resume/custom", "routes/resume-customizer.tsx"),
  route("/p/:slug", "routes/p.$slug.tsx"),
  layout("routes/editor.tsx", [
    route("/editor", "routes/editor.basic.tsx"),
    route("/editor/work", "routes/editor.work.tsx"),
    route("/editor/skills", "routes/editor.skills.tsx"),
    route("/editor/social", "routes/editor.social.tsx"),
    route("/editor/stats", "routes/editor.stats.tsx"),
    route("/editor/projects", "routes/editor.projects.tsx"),
    route("/editor/testimonials", "routes/editor.testimonials.tsx"),
  ]),
] satisfies RouteConfig;
